version: '3'
services:
    employeecare:
        container_name: employee-care
        image: rabnmgr7/employee-care:latest
        ports:
            - 8081:8080
    mysql:
        container_name: employee-care-db
        image: rabnmgr7/employee-care-db:latest
        volumes:
            - appvolume:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    appvolume:  
